### PR TITLE
Abort install if a JDK process to be installed over is running

### LINKED ISSUE #117: Better handling of java process in use
Since the gradle daemon is likely to be running, the reinstalling java leads to an exception.

Potential solutions:

- Detect if the installed version of java is the same as the to be installed version, and skip. It seems like the release file in the jdk folder could be used for this.
- Kill any java processes using the frc jdk (probably dangerous, and possibly not OS agnostic)
- Catch the exception and display a better error message recommending a reboot

### PR DESCRIPTION
**Pull request by ThadHouse**
Closes #117 

In that issue, a slightly modified option 3 was chosen. It search for any exes running out of the JDK folder. If any are found, a popup is displayed telling the user to reboot.

Decided against killing processes, as its not reliable to do so. Also decided against detecting the jdks, as mid season updates can result in the MSVC runtimes changing without the JDK version changing. So we'd have to hash a bunch of files, and its probably not worth it.

### CODE REVIEW

File: WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs [hunk 1]
```diff
@@ -435,6 +435,61 @@ private async Task RunVsCodeSetup(CancellationToken token)
...
+                    }
+                    catch
+                    {
+                        // Do nothing. We don't want this code to break.
+                        return false;
+                    }
+                });
+                if (foundRunningExe)
+                {
+                    string msg = "Running JDK processes have been found. Installation cannot continue. Please restart your computer, and rerun this installer without running thing else (including VS Code)";
```
Comment (Daltz333) [inline WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs:482]: Theres a typo here
